"""Giving each agent a container of its own: the files that describe one.

This module writes three things and reads one:

* a compose file naming a service per agent, plus the volumes and the private
  network each needs;
* a Dockerfile per agent, built on the shared agent image, carrying whatever
  that agent asked for;
* a token per agent, so the engine and that agent's host share a secret nobody
  else does;

and it reads ``runtime.packages`` and ``Dockerfile.include`` from the agent's own
directory, which is how an operator says "this one needs a JDK".

Everything generated lands under the deployment's ``conf`` directory and is
rewritten whole on every sync. Nothing here is edited by hand — the file says so
at the top, and a deployment's own compose overrides still go in ``compose.d``,
which this never touches.

Paths are deliberately the SAME on both sides: the agents directory and the
skill library are mounted where the engine has them, so a filename in a chat
message means the same thing in both containers. The two directories that cannot
be shared — session files and the agent's own files — are one volume per agent,
which is the isolation this whole arrangement is for.
"""

import logging
import secrets
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from crucible.ports.agent import AgentSpec
from impi.provisioning import agent_env_key, set_env_key

logger = logging.getLogger(__name__)

# The shared base image every agent's own image is built on.
BASE_IMAGE = "localhost/impi-agent:local"
# Service and volume naming. One prefix, used everywhere, so an operator reading
# `compose ps` can tell an agent's container from the engine's at a glance.
SERVICE_PREFIX = "agent-"
# The port a host listens on inside its own container. Never published.
HOST_PORT = 8427
# The per-agent key holding the secret the engine and the host share.
TOKEN_KIND = "HOST_TOKEN"
# What an operator drops in an agent's directory to add build steps.
INCLUDE_FILE = "Dockerfile.include"

# Container-fixed paths. The first two are the engine's own, on purpose.
AGENTS_MOUNT = "/app/agents"
SKILLS_MOUNT = "/app/skills"
SESSIONS_MOUNT = "/app/sessions"
FILES_MOUNT = "/app/files"
EXTENSION_PATH_IN_IMAGE = "/app/extension/index.ts"
# Where the broker's identities are mounted, in both containers. The engine
# mounts the whole directory because it is what hands them out; an agent gets
# its own two files and the authority, and nothing else.
CERTS_MOUNT = "/app/conf/certs"

_GENERATED_HEADER = """\
# GENERATED by `impi agent sync` — every edit here is lost on the next one.
#
# One service per agent: its runtime runs there instead of inside the engine, so
# what that agent depends on, what it can read and what credentials it holds are
# its own. The engine reaches each host over a private network the agent shares
# with nobody else.
#
# A deployment's own compose overrides belong in compose.d/, which is merged
# after this file and is never generated.
"""


class RenderError(Exception):
    """The deployment cannot be described — an agent asked for something that
    cannot be built or mounted."""


@dataclass(frozen=True)
class AgentBuild:
    """One agent's build: what it asked for, on top of the shared image."""

    name: str
    apt: tuple[str, ...] = ()
    npm: tuple[str, ...] = ()
    pip: tuple[str, ...] = ()
    include: str = ""

    @property
    def customized(self) -> bool:
        return bool(self.apt or self.npm or self.pip or self.include.strip())

    @property
    def image(self) -> str:
        # Always its own tag, even when it adds nothing: the image is then one
        # metadata layer over the shared base, and every agent is built and
        # rebuilt the same way. The alternative — sharing the base tag when
        # there are no extras — makes two services claim one image and leaves
        # the order they are built in deciding what that image contains.
        return f"localhost/impi-agent-{self.name}:local"


@dataclass(frozen=True)
class Deployment:
    """The axes this render has to fit alongside."""

    agents_mount_source: str = "${IMPI_AGENTS_DIR:?set in compose.env}"
    home: str = "${IMPI_HOME:?set in compose.env}"
    # The same variable without the guard, for the one place it appears INSIDE
    # another expansion — compose does not read a `:?` nested in a default.
    home_plain: str = "${IMPI_HOME}"
    with_vault: bool = False
    with_browser: bool = False
    extensions_dir: bool = False  # the agents directory has an _extensions/
    builds: Sequence[AgentBuild] = field(default_factory=tuple)
    # Rootless podman maps the operator's user into the container, and a service
    # WITHOUT that mapping gets a different one. Two containers sharing a volume
    # then see two different owners on the same directory: the agent cannot write
    # what the engine reads, and a 0600 certificate the operator was issued is
    # unreadable to the agent it belongs to. The engine's own mapping comes from
    # compose.podman.yaml; these services are generated, so theirs comes from here.
    rootless: bool = False
    # Which agents have a certificate issued. Only those get one mounted: a bind
    # mount of a file that does not exist is a directory on one runtime and an
    # error on the other, and neither is what an operator meant.
    with_identity: frozenset[str] = frozenset()


# --- reading what an agent asked for -----------------------------------------


def read_build(spec: AgentSpec) -> AgentBuild:
    """An agent's build extras, from its own directory.

    ``runtime.packages`` is read straight from ``agent.yaml`` rather than through
    ``AgentSpec``: which Debian packages a deployment installs is not part of what
    an agent IS, and the neutral spec has no business carrying it.
    """
    manifest = spec.profile_dir / "agent.yaml"
    packages: object = {}
    if manifest.is_file():
        loaded = yaml.safe_load(manifest.read_text(encoding="utf-8")) or {}
        runtime = loaded.get("runtime") if isinstance(loaded, dict) else None
        if isinstance(runtime, dict):
            packages = runtime.get("packages") or {}
    if not isinstance(packages, dict):
        raise RenderError(
            f"{spec.name}: runtime.packages must be a mapping of apt/npm/pip lists"
        )
    include_path = spec.profile_dir / INCLUDE_FILE
    include = include_path.read_text(encoding="utf-8") if include_path.is_file() else ""
    return AgentBuild(
        name=spec.name,
        apt=_names(packages.get("apt"), spec.name, "apt"),
        npm=_names(packages.get("npm"), spec.name, "npm"),
        pip=_names(packages.get("pip"), spec.name, "pip"),
        include=include,
    )


def _names(raw: object, agent: str, kind: str) -> tuple[str, ...]:
    if raw is None:
        return ()
    if not isinstance(raw, list) or any(not isinstance(item, str) for item in raw):
        raise RenderError(f"{agent}: runtime.packages.{kind} must be a list of names")
    for name in raw:
        # A package name, not a shell fragment. Anything cleverer belongs in
        # Dockerfile.include, where it is visible as what it is.
        if not name or any(character.isspace() for character in name):
            raise RenderError(
                f"{agent}: {name!r} is not a package name — put shell in "
                f"{INCLUDE_FILE} instead"
            )
    return tuple(raw)


# --- the per-agent Dockerfile -------------------------------------------------


def render_dockerfile(build: AgentBuild) -> str:
    lines = [
        "# GENERATED by `impi agent sync` — edits here are lost on the next one.",
        "#",
        f"# {build.name}'s image: the shared agent image plus what this agent asked",
        "# for in its agent.yaml (runtime.packages) and its Dockerfile.include.",
        f"FROM {BASE_IMAGE}",
        "",
        "# Root for the build steps only. The footer below puts it back, and the",
        "# engine relies on that: a runtime running as root in its own container",
        "# would give back the isolation this arrangement exists to create.",
        "USER root",
    ]
    if build.apt:
        lines += [
            "RUN apt-get update \\",
            " && apt-get install -y --no-install-recommends \\",
            "      " + " ".join(build.apt) + " \\",
            " && rm -rf /var/lib/apt/lists/*",
        ]
    if build.npm:
        lines += ["RUN npm install -g " + " ".join(build.npm) + " && npm cache clean --force"]
    if build.pip:
        lines += ["RUN pip install --no-cache-dir --break-system-packages " + " ".join(build.pip)]
    if build.include.strip():
        lines += [
            "",
            f"# --- from this agent's {INCLUDE_FILE} ---",
            build.include.rstrip(),
            "# --- end ---",
        ]
    lines += [
        "",
        "# The footer is a contract, not decoration: the host runs as the",
        "# deployment's user and is started the same way in every agent image.",
        'ARG IMPI_UID=1000',
        'ARG IMPI_GID=1000',
        'USER ${IMPI_UID}:${IMPI_GID}',
        'CMD ["runtime-relay", "serve"]',
        "",
    ]
    return "\n".join(lines)


# --- the compose file ---------------------------------------------------------


def render_compose(deployment: Deployment) -> str:
    names = [build.name for build in deployment.builds]
    out = [_GENERATED_HEADER, "services:"]
    for build in deployment.builds:
        out.append(_agent_service(build, deployment))
    out.append(_engine_service(names, deployment))
    if deployment.with_vault:
        out.append(_vault_service(names))
    if deployment.with_browser:
        out.append(_browser_service(names))
    out.append(_networks(names, deployment))
    out.append(_volumes(names))
    return "\n".join(out)


def _agent_service(build: AgentBuild, deployment: Deployment) -> str:
    name = build.name
    home = deployment.home
    agents = deployment.agents_mount_source
    lines = [
        f"  {SERVICE_PREFIX}{name}:",
        "    build:",
        f"      context: {home}/conf/agents/{name}",
        "      args:",
        '        IMPI_UID: "${IMPI_UID:-1000}"',
        '        IMPI_GID: "${IMPI_GID:-1000}"',
        f"    image: {build.image}",
        "    restart: unless-stopped",
        "    env_file:",
        f"      - {home}/conf/agents/{name}.env",
        "    environment:",
        f"      RUNTIME_RELAY_AGENT: {name}",
        f"      RUNTIME_RELAY_PROFILE_DIR: {AGENTS_MOUNT}/agents/{name}",
        f"      RUNTIME_RELAY_LIBRARY_DIR: {SKILLS_MOUNT}",
        f"      RUNTIME_RELAY_SESSION_DIR: {SESSIONS_MOUNT}",
        f"      RUNTIME_RELAY_EXTENSIONS: {EXTENSION_PATH_IN_IMAGE}",
        f'      RUNTIME_RELAY_PORT: "{HOST_PORT}"',
        "      RUNTIME_RELAY_WORK_DIR: /tmp/runtime-relay",
    ]
    if deployment.extensions_dir:
        lines.append(f"      RUNTIME_RELAY_EXTENSIONS_DIR: {AGENTS_MOUNT}/_extensions")
    if name in deployment.with_identity:
        # Pointed at explicitly rather than derived from the agent's name: the
        # directory holds one identity now, not everybody's, so there is nothing
        # to pick between — and being explicit is what makes that visible here.
        lines += [
            '      SECRET_BROKER_URL: "https://ward:8425"',
            f"      SECRET_BROKER_CERT: {CERTS_MOUNT}/{name}.crt",
            f"      SECRET_BROKER_KEY: {CERTS_MOUNT}/{name}.key",
            f"      SECRET_BROKER_CA: {CERTS_MOUNT}/ca.crt",
        ]
    lines += [
        "    volumes:",
        # Read-only: the agent's own directory is the operator's to write, and
        # the runtime only reads it. Its advisory lock on settings fails there
        # and it carries on, which is already the case for a read-only profile.
        f"      - {agents}/agents/{name}:{AGENTS_MOUNT}/agents/{name}:ro,z",
        f"      - ${{IMPI_SKILLS_DIR:-{deployment.home_plain}/skills}}:{SKILLS_MOUNT}:ro,z",
        f"      - {SERVICE_PREFIX}{name}-sessions:{SESSIONS_MOUNT}",
        f"      - {SERVICE_PREFIX}{name}-files:{FILES_MOUNT}/{name}",
        "      - pi-auth:/home/impi/.pi",
    ]
    if deployment.extensions_dir:
        lines.append(f"      - {agents}/_extensions:{AGENTS_MOUNT}/_extensions:ro,z")
    if name in deployment.with_identity:
        # Three files, read-only, and NOT the directory they came from. This is
        # the line that turns "every agent can read every agent's key" into a
        # sentence about the past.
        lines += [
            f"      - {home}/certs/{name}.crt:{CERTS_MOUNT}/{name}.crt:ro,z",
            f"      - {home}/certs/{name}.key:{CERTS_MOUNT}/{name}.key:ro,z",
            f"      - {home}/certs/ca.crt:{CERTS_MOUNT}/ca.crt:ro,z",
        ]
    if deployment.rootless:
        lines.append(
            '    userns_mode: "keep-id:uid=${IMPI_UID:-1000},gid=${IMPI_GID:-1000}"'
        )
    lines += [
        f"    networks: [{SERVICE_PREFIX}{name}]",
        "    healthcheck:",
        '      test: ["CMD", "python", "-c", "import urllib.request as u;'
        f' u.urlopen(\'http://127.0.0.1:{HOST_PORT}/health\', timeout=2)"]',
        "      interval: 30s",
        "      start_period: 10s",
        "",
    ]
    return "\n".join(lines)


def _engine_service(names: Sequence[str], deployment: Deployment) -> str:
    networks = ["default"]
    if deployment.with_browser:
        networks.append("browser")
    networks += [f"{SERVICE_PREFIX}{name}" for name in names]
    lines = [
        "  impi:",
        "    environment:",
        # The engine stops forking runtimes and starts asking for them.
        '      AGENT_HOSTS_ENABLED: "true"',
        # The tool server is no longer talking to processes on its own loopback.
        "      TOOL_SERVER_HOST: 0.0.0.0",
        "      TOOL_PUBLIC_URL: http://impi:8422",
        # Out of the engine's data volume, so each agent's own directory can be
        # a volume of its own mounted at the same path on both sides.
        f"      ATTACHMENTS_DIR: {FILES_MOUNT}",
        f"    networks: [{', '.join(networks)}]",
    ]
    lines.append("    volumes:")
    # The parent holds the agents that still run here — the engine's own. The
    # per-agent volumes are nested inside it, which both runtimes resolve by
    # mounting the deeper path last; each agent then sees its own directory and
    # only its own, at the same path the engine names it by.
    lines.append(f"      - impi-files:{FILES_MOUNT}")
    lines += [
        f"      - {SERVICE_PREFIX}{name}-files:{FILES_MOUNT}/{name}"
        for name in names
    ]
    lines.append("")
    return "\n".join(lines)


def _vault_service(names: Sequence[str]) -> str:
    # The broker answers at `ward` on every network an agent might ask from, and
    # the store carries the broker's network, so the alias belongs to the store.
    lines = ["  vault:", "    networks:", "      default:", "        aliases: [ward]"]
    for name in names:
        lines += [f"      {SERVICE_PREFIX}{name}:", "        aliases: [ward]"]
    lines.append("")
    return "\n".join(lines)


def _browser_service(names: Sequence[str]) -> str:
    networks = ["browser"] + [f"{SERVICE_PREFIX}{name}" for name in names]
    return "\n".join([
        "  browser:",
        f"    networks: [{', '.join(networks)}]",
        "",
    ])


def _networks(names: Sequence[str], deployment: Deployment) -> str:
    # Every network any service here names has to be declared: naming one at all
    # makes compose validate the rest, and a missing entry fails the whole merge
    # rather than one service.
    lines = ["networks:", "  default:"]
    if deployment.with_browser:
        lines.append("  browser:")
    lines += [f"  {SERVICE_PREFIX}{name}:" for name in names]
    lines.append("")
    return "\n".join(lines)


def _volumes(names: Sequence[str]) -> str:
    lines = ["volumes:", "  pi-auth:", "  impi-files:"]
    for name in names:
        lines += [
            f"  {SERVICE_PREFIX}{name}-sessions:",
            f"  {SERVICE_PREFIX}{name}-files:",
        ]
    lines.append("")
    return "\n".join(lines)


# --- writing it all out -------------------------------------------------------


def ensure_token(dotenv_path: str | Path, conf_dir: Path, agent: str) -> str:
    """The secret this agent's host and the engine share. Created once and kept:
    rotating it on every sync would mean a running host answering with a token
    the engine has already forgotten."""
    key = agent_env_key(agent, TOKEN_KIND)
    env_file = conf_dir / "agents" / f"{agent}.env"
    existing = _read_value(env_file, "RUNTIME_RELAY_TOKEN")
    token = existing or secrets.token_hex(24)
    env_file.parent.mkdir(parents=True, exist_ok=True)
    if not existing:
        env_file.write_text(f"RUNTIME_RELAY_TOKEN={token}\n", encoding="utf-8")
        env_file.chmod(0o600)
    set_env_key(dotenv_path, key, token)
    return token


def _issued(builds: Sequence[AgentBuild], certs_dir: Path | None) -> frozenset[str]:
    """The agents whose broker identity already exists. An agent without one is
    left without the mount rather than given a broken path: it can be issued a
    certificate and synced again, and until then it simply cannot ask."""
    if certs_dir is None or not (certs_dir / "ca.crt").is_file():
        return frozenset()
    return frozenset(
        build.name
        for build in builds
        if (certs_dir / f"{build.name}.crt").is_file()
        and (certs_dir / f"{build.name}.key").is_file()
    )


def _read_value(path: Path, key: str) -> str:
    if not path.is_file():
        return ""
    for line in path.read_text(encoding="utf-8").splitlines():
        name, _, value = line.partition("=")
        if name.strip() == key:
            return value.strip()
    return ""


def sync(
    specs: Iterable[AgentSpec],
    *,
    dotenv_path: str | Path,
    conf_dir: Path,
    agents_path: Path,
    with_vault: bool = False,
    with_browser: bool = False,
    rootless: bool = False,
    certs_dir: Path | None = None,
) -> list[str]:
    """Write everything a deployment needs to run these agents in containers.

    Returns one line per agent, for the operator to read. Idempotent: the same
    agents produce the same files, and an existing token is kept.
    """
    builds = [read_build(spec) for spec in specs]
    identities = _issued(builds, certs_dir if with_vault else None)
    deployment = Deployment(
        with_vault=with_vault,
        with_browser=with_browser,
        rootless=rootless,
        extensions_dir=(agents_path / "_extensions").is_dir(),
        builds=builds,
        with_identity=identities,
    )
    notes: list[str] = []
    for build in builds:
        target = conf_dir / "agents" / build.name
        target.mkdir(parents=True, exist_ok=True)
        (target / "Dockerfile").write_text(render_dockerfile(build), encoding="utf-8")
        ensure_token(dotenv_path, conf_dir, build.name)
        note = f"{build.name}: {'extra build steps' if build.customized else 'no extras'}"
        if with_vault and build.name not in identities:
            note += f"; no broker certificate yet (impi ward cert {build.name})"
        notes.append(note)
    compose_path = conf_dir / "agents.compose.yaml"
    compose_path.write_text(render_compose(deployment), encoding="utf-8")
    logger.info("Wrote %s for %d agent(s)", compose_path, len(builds))
    return notes
